### ISSUE TITLE
Internet Connectivity Flag

### ISSUE THREAD

**Issue by Kaizoku01** [Kaizoku01/Weatheria#1]
### Tasks
_priority = 3_
- [x] check for internet connectivity upon launching of the app.
- [x] continue listening to the internet connectivity throughout app lifecycle {provider/bloc}
- [x] create appropriate alert dialog that matches with the app ui.
- [x] create appropriate loading animation that matches the app ui, and remove the circular progress indicator when future at home screen is rebuild.
