### ISSUE TITLE
Complete the API calling of the TimeWeatherCard

### ISSUE THREAD

**Issue by Kaizoku01** [Kaizoku01/Weatheria#3]
### Tasks
_priority = 1_

- [ ] get response {only temperature}  from openWeatherApi for the temperature forcast daywise.
- [ ] convert the data into usable format using fromJson method present already in WeatherModel.
- [ ] make a seperate model `ForcastWeatherModel` for this.
- [ ] implement the complete api get cycle and display the ourput over ui
