### ISSUE TITLE
Implement weather retreiving using City Name

### ISSUE THREAD

**Issue by Kaizoku01** [Kaizoku01/Weatheria#4]
### Tasks
_priority = 1_

- [ ] Implement a search field delegate on the search icon next to the city name .
- [ ] For the query of the city_names  perform sharding on the city_list.json file upto three characters of the city name and sort them lexicographically.
- [ ] create the fetch call after the user has type three character in the search field and stored the json entries as List<Map<string, dynamic>> and to be used as searching delegate
