### ISSUE TITLE
Complete Quote Text Segment

### ISSUE THREAD

**Issue by Kaizoku01** [Kaizoku01/Weatheria#6]
### Tasks
_priority = 1_

- [x] make another model for quote named as `QuoteDataModel`
- [x] Make another Api service file named `quote_service.dart` containing class named `QuoteService`
- [x] implement Api fetch methods, use fromJson() conversion to store the quote response fetched.
- [x] Creater a provider for quote named `QuoteProvider` store the fetched `QuoteDataModel` here.
- [x] Display fetched data on Home Screen

Api link : https://api-ninjas.com/api/quotes

### Fetching Behaviour

- Make a List of String  containing quote categories which will be used while fetching
- pick random quote category and plant that in api fetch call.
